# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-03 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('-date',)},
        ),
    ]
