# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-16 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_photo_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
