# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-04 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20190703_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='roll_id',
            field=models.IntegerField(default=None, primary_key=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='uuid',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='id',
            field=models.IntegerField(primary_key=True),
        ),
    ]
